### PR TITLE
Tailing stop bug fix

### PR DESCRIPTION
**Pull request by arunmathew88**
Fix for Issue #98 and Issue #97, which causes tailing to stop at times.

### CODE REVIEW

**Comment by cheesestraws** [comment]
I've been running this patch for a few days and it certainly seems to fix my issue #94

**Comment by arunmathew88** [comment]
Thanks Rob,
              I've not got any communication from the hpcloud
authors/moderators regarding merging the pull request yet.

**Comment by arunmathew88** [comment]
@Nino-K or other admins, any update on this?

**Comment by arunmathew88** [comment]
The issue corresponding to the fix can be reproduced by tailing  a log file which is logrotated (renamed and recreated) frequently.

**Comment by TerraTech** [comment]
@Nino-K can we get this merged please?  Thanks!

**Comment by Nino-K** [comment]
@arunmathew88 Thanks for your contribution, it's merged now.

**Comment by arunmathew88** [comment]
@Nino-K Thanks for the merge.

**Pull request merged**
