### PR TITLE
Revert "Tailing stop bug fix"

### PR DESCRIPTION
**Pull request by Nino-K**
Reverts hpcloud/tail#99

### CODE REVIEW

**Comment by TerraTech** [comment]
@Nino-K Did this patch go sideways with a test?

**Comment by Nino-K** [comment]
@TerraTech yes, broke the build but it's merged now and the build is green.

**Comment by arunmathew88** [comment]
@Nino-K So as of now  hpcloud/tail#99 is merged and there is no problem?

**Comment by Nino-K** [comment]
@arunmathew88 thanks for your contribution. So far so good, I tested it myself and did not come across any issues, the test coverage in this project is pretty low, I will have to through some tests in there to cover some of these cases.

**Comment by arunmathew88** [comment]
Thanks @Nino-K .

**Pull request merged**
