### PR TITLE
Single shared Watcher used to avoid inotify limit

### PR DESCRIPTION
**Pull request by andyouyang22**
When we were using this tail library, we found that the system limit on inotify watches would become an issue when we we try to tail many files at once (if many Tail objects are open simultaneously). To circumvent this, we changed the InotifyTracker struct to contain a Watcher that is shared by all Tail objects that are created.

### CODE REVIEW

**Comment by srid** [comment]
@andyouyang22 we already implemented the shared watcher in #53. i'll close this PR unless you wish to reopen it for any reason.

**Comment by andyouyang22** [comment]
Sridhar,

This pull request goes further than #53 and uses a single shared Watcher
for *all* Tail objects that are created. We originally made this change
because we found that we would hit the system inotify limit if we were
tailing too many files at once.

Andy

**Comment by tsuna** [comment]
Hi, I rebased our changes and added an additional fix for a race in truncation detection.  Are you guys interested in merging our enhancements?

**Comment by Nino-K** [comment]
@srid any suggestions on merging this in?

**Comment by tsuna** [comment]
Here's a short description of the changes:

* Use a single inotify watcher regardless of the number of files being tailed.  Without this one easily runs into the maximum number of inotify watches allowed by the kernel.
* If a process gets suspended and then resumed, the library was printing a spurious warning.
* Fix various race conditions.
* Upgrade to fsnotify v1 (from v0, which is on life support at this point and not guaranteed to get bug fixes).

**Comment by Nino-K** [comment]
@tsuna , @andyouyang22 Thanks for you contributions, it's merged.

**Pull request merged**
