### PR TITLE
Fix fsnotify repository relocation

### PR DESCRIPTION
**Pull request by promiseofcake**
The https://github.com/go-fsnotify/fsnotify redirect has been disabled and replaced with an empty repo, the new path for gopkg.in is: http://gopkg.in/fsnotify/fsnotify.v1 as of yesterday.

* Modify `fsnotify` import paths to: gopkg.in/fsnotify/fsnotify.v1
* Copy `vendor/fsnotify.v1` to the new import path

### CODE REVIEW

**Comment by promiseofcake** [comment]
Fixes #136

**Comment by c9s** [comment]
@Nino-K can we merge this PR asap ? the build is now broken, we can't deliver the release and the CI is not working now...

**Comment by idanya** [comment]
any news on that merge? Really need this to release ....

**Comment by promiseofcake** [comment]
@idanya, @c9s, depending on your build system you should be able to use the pre-merge commit from our public fork by modifying your `repo` param (glide), `source` override (dep) or something similar for other package tools, ie for Bazel:

```
go_repository(
  name = "com_github_hpcloud_tail",
  importpath = "github.com/hpcloud/tail",
  remote = "git@github.com:vsco/tail.git",
  vcs = "git",
  commit = "000912af8de2d2b9d184786b4cf4c3542b7884e5"
)
```

**Comment by idanya** [comment]
Yes, I'm using govendor and already did the same (forked and merged your commit). I'd rather it be merged here but I guess that will do for now :\

**Comment by c9s** [comment]
Please merge....

**Comment by kyleconroy** [comment]
If you're using dep, add the following to your `Gopkg.toml`:

```
[[override]]
  name = "github.com/hpcloud/tail"
  source = "git@github.com:vsco/tail.git"
  revision = "000912af8de2d2b9d184786b4cf4c3542b7884e5"
```

**Comment by mattayes** [comment]
@florindragos Are you the only person with write-access to this project?

**Comment by mattayes** [comment]
@promiseofcake The `fsnotify` project prefers `github.com/fsnotify/fsnotify` to the `gopkg.in` link: https://godoc.org/github.com/fsnotify/fsnotify.

**Comment by promiseofcake** [comment]
@mattayes, thanks for the link. In order to not conflate changes, I would be more than happy to make that change once we get this merged in.

**Comment by samkreter** [comment]
+1 on this merging. This is blocking a few deployments.

**Comment by mattayes** [comment]
@Nino-K do you still have write access to this repo/time to review this?

**Comment by samkreter** [comment]
This is a key blocker right now. Any estimate on when it can be merged?

**Comment by tcolgate** [comment]
This also blocks use of hpcloud/tail with vgo (at least I've been unable to get it working)

**Comment by promiseofcake** [comment]
@sergei-utinski, do you know anyone who can help us out?

**Comment by promiseofcake** [comment]
Thanks @sergei-utinski! What are the plans for this repo? Can community members get write access, or should we look into housing this repo somewhere else?

**Pull request merged**
